name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: make install

    - name: Build Binary Executable
      run: make build

    # - name: Run Tests
    #   run: make test

    - name: Remove Virtual Environment
      run: make clean
