name: Makefile CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Install Dependencies
      run: make install

    - name: Build Binary Executable
      run: make build
    
    - name: Upload Executable
      uses: actions/upload-artifact@v4
      with:
        name: TREND
        path: dist/ 

    - name: Run Tests
      run: make test

    - name: Remove Virtual Environment
      run: make clean
